Aqui está um código simples com sklearn para testar a execução de Python no Codespace com uma Decision Tree:

In [55]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [65]:
def carregar_dataset(dataset_func):
    """
    Descrição:
        Essa função é usada para carregar um dataset do Scikit-learn, separando-o em dados e rótulos.

    Parâmetros:
        dataset_func: função
            Função para carregar o dataset (por exemplo, `load_iris`, `load_digits`).

    Retorno:
        dataset: objeto
            O dataset completo carregado.
        X: array
            As características (dados) do dataset.
        y: array
            Os rótulos do dataset.
    """
    # Carregar o dataset especifico
    dataset = dataset_func()
    X = dataset.data
    Y = dataset.target

    return dataset, X, Y

In [70]:
def dividir_treinamento(X, Y, test_size=0.2, random_state=42):
    """"
    Descrição: 
        Função usada para Dividir matrizes ou matrizes em subconjuntos de trem aleatório e teste. para isso vou usar a função train_test_split()
        
    Parametrôs: data, label, test_size, random_state
        X = Características de entrada
        Y = Rotulos
        test_size = representar a proporção do conjunto de dados para incluir na divisão de teste.
        random_state = Controla o embaralhamento aplicado aos dados antes de aplicar a divisão. Passe um int para saída reprodutível em várias chamadas de função.

    Retorno: X_train, X_test, y_train, y_test
        X_train = dados de treinamento separado
        X_test = dados de teste separado
        y_train = rotulos de treinamento
        y_test = rotulos de teste
    """
    # Dividir o dataset em treinamento e teste
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=random_state)

    return X_train, X_test, y_train, y_test

In [77]:
def treinando_modelo(modelo, X_train, y_train, X_test, random_state=None):
    """
    Descrição:
        Função para treinar um modelo de classificação usando o sklearn.
    
    Parâmetros:
        modelo: classificador
            O modelo que queremos usar como classificador (por exemplo, DecisionTreeClassifier, RandomForestClassifier).
        X_train: array-like
            Dados de treinamento.
        X_test: array-like
            Dados de teste.
        y_train: array-like
            Rótulos do conjunto de treinamento.
        random_state: int, opcional
            Controla o embaralhamento aplicado aos dados antes de aplicar a divisão. Passe um int para saída reprodutível.

    Retorno:
        modelo_treinado: classificador
            O modelo treinado.
        y_pred: array
            Previsões do modelo para o conjunto de teste.
    """
    # Verificar se o modelo aceita o parâmetro random_state
    if 'random_state' in modelo().get_params().keys():
        modelo_treinado = modelo(random_state=random_state)
    else:
        modelo_treinado = modelo()

    # Treinar o modelo
    modelo_treinado.fit(X_train, y_train)

    # Prever as classes para o conjunto de teste
    y_pred = modelo_treinado.predict(X_test)

    return modelo_treinado, y_pred

In [80]:
dataset, X, Y = carregar_dataset(load_iris)
# Agora, você pode usar `X` e `y` em outras partes do seu código
print("Características (X):", X[:5])
print("Rótulos (y):", Y[:5])

X_train, X_test, y_train, y_test = dividir_treinamento(X, Y)

modelo_treinado, y_pred = treinando_modelo(DecisionTreeClassifier, X_train, y_train, X_test, random_state=42)
print("Precisão:", modelo_treinado.score(X_test, y_test))

Características (X): [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Rótulos (y): [0 0 0 0 0]
Precisão: 1.0
